### PR TITLE
APP-415: Upload test reports

### PR DESCRIPTION
**Pull request by hedvigoscar**
### Checklist

- [ ] Functionality is covered by an integration test
- [ ] Functionality is accessible in engineering mode

### CODE REVIEW

**Review by hugokallstrom — APPROVED** [review]
What does this do? :)

**Comment by hedvigoscar** [comment]
Good question 😬 This PR makes it so that after running tests in Github Actions, regardless of whether the tests pass or fail, the test results get uploaded as an artifact to Github Actions.

That means that when a test fails, we can download the test report and get some proper context to what actually went wrong. I think this will aid us in maintaining test suite stability over time 🙂

**Comment by hedvigoscar** [comment]
For example, the tests fail in this PR. Now I can download the test report and dig through it to see what's up 🙂

**Comment by hugokallstrom** [comment]
> Good question 😬 This PR makes it so that after running tests in Github Actions, regardless of whether the tests pass or fail, the test results get uploaded as an artifact to Github Actions.
> 
> That means that when a test fails, we can download the test report and get some proper context to what actually went wrong. I think this will aid us in maintaining test suite stability over time 🙂

Thats great! 👍

**Pull request merged**
