### PR TITLE
Update build config to only have showkase on non production builds

### PR DESCRIPTION
**Pull request by StylianosGakis**
Updates after input taken from https://github.com/airbnb/Showkase/issues/189 issue

### CODE REVIEW

**Review by vinaygaba — COMMENTED** [review]
You can also move your showkaseRoot implementation into the debug sourceSet instead of adding it in main.

**Comment by hedvigoscar** [comment]
@vinaygaba We actually have it under the `engineering`-sourceSet, which is not included in release-builds 🙂

**Comment by hedvigoscar** [comment]
Also, thanks for checking our little codebase out 😉

**Review by hedvigoscar — APPROVED** [review]
lgtm!

**Pull request merged**
