### PR TITLE
APP-1651: Make insurance query not show stale data after approving a moving flow

### PR DESCRIPTION
**Pull request by StylianosGakis**
Judging from the logs:
`2022-05-05T08:12:41.157000+00:00 com.hedvig.test.app: 23377:23474 D/a: Cache HIT for operation InsuranceQuery`

The cache is hit when it should actually try to fetch from the network.

Tested this change by using the original code:
- signing a new member
- approved the accident cross sell
- refreshing the page and seeing the cache being hit despite the giraffe query returning both contracts at this point

After this commit, did this:
- unsigned old member and started fresh
- signed a new member
- approved the accident cross sell
- now the page even before refreshing properly fetches the new data that the screens should be showing.

### CODE REVIEW

**Review by hugokallstrom — APPROVED** [review]
LGTM

**Comment by oscarnylander** [comment]
I'm curious - why do we need to do this?

**Comment by oscarnylander** [comment]
So, if I understand it correctly, the issue is that the cache is stale once the moving flow has been completed?

Wouldn't the correct solution then be to issue a cache invalidation when the moving flow has been completed? 🤔

**Comment by StylianosGakis** [comment]
> So, if I understand it correctly, the issue is that the cache is stale once the moving flow has been completed?
> 
> Wouldn't the correct solution then be to issue a cache invalidation when the moving flow has been completed? 🤔

Yeah that is indeed correct, I completely forgot that we can actually clear the cache like that. Let me look into how that could be done instead 👀

**Comment by StylianosGakis** [comment]
Please take a peek at the new commit. I see we had a `...andClearCache` function which didn't actually clear the cache any more. And if it does, it solves this problem of ours actually as I see it. Removed the network_only part of the insurance query too

**Review by oscarnylander — APPROVED** [review]
lgtm

**Pull request merged**
