### PR TITLE
Debug feature manager

### PR DESCRIPTION
**Pull request by hugokallstrom**
image

### CODE REVIEW

**Comment by hedvigoscar** [comment]
Agree with @StylianosGakis here, I think we should move this to the engineering screen.

**Comment by StylianosGakis** [comment]
> Agree with @StylianosGakis here, I think we should move this to the engineering screen.

Hmm I would say it should be there *in addition* to the profile screen. Let's make their lives easier, no reason for this to be hidden in engineering mode exclusively.

**Comment by hedvigoscar** [comment]
What's the value-add of having it in two places? 🤔 I'm a bit wary of the risk of showing engineering-tooling on the production-screens for end-users that shouldn't see it.

**Comment by StylianosGakis** [comment]
> What's the value-add of having it in two places? 🤔 I'm a bit wary of the risk of showing engineering-tooling on the production-screens for end-users that shouldn't see it.

Ok we can hide it and get feedback from them if it's okay

**Comment by hugokallstrom** [comment]
Added different implementations depending on build variant. This way we make sure to not have any feature flag activity code in prod.

**Pull request closed without merging**
